all:
	gcc execute.c -o execute
	gcc create_processes.c -o processes
	gcc thread.c -o thread -pthread
processes:
	gcc create_processes.c -o processes
execute:
	gcc execute.c -o execute
thread:
	gcc thread.c -o thread -pthread
